apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: activities-app-dev
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/florient2016/OCP-Argocd-app.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true