apiVersion: apps/v1
kind: Deployment
metadata:
  name: activities-app
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: activities
  template:
    metadata:
      labels:
        app: activities
    spec:
      containers:
        - name: activities
          image: docker.io/komlan2019/activities:842eb15f785b5ec6d9f3f4f864bbe1b56382a2e8
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "128m"